name: LateX Build
on:
  push:
    branches: [ main ]
    tags:
      - '**'
  workflow_dispatch:
jobs:
  BuildLatexJob:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Git repo
        uses: actions/checkout@v2
      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          #pre_compile: "tlmgr update --self --all"
          args: "-pdf -jobname=Lirussi-Igor-CV -file-line-error -halt-on-error -interaction=nonstopmode -logfilewarninglist"
          post_compile: "latexmk -c"
      - name: Compile LaTeX Document-ita 
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main-ita.tex
          #pre_compile: "tlmgr update --self --all"
          args: "-pdf -jobname=Lirussi-Igor-CV-Ita -file-line-error -halt-on-error -interaction=nonstopmode -logfilewarninglist"
          post_compile: "latexmk -c"
      - name: Split log
        if: failure()
        shell: bash
        run: cat main.log | grep -n -E 'LaTeX Error|LaTeX Warning|Undefined' > small.log
      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: Logs
          path: |
            main.log
            small.log 
      - name: Print small log
        if: failure()
        shell: bash
        run: cat small.log >&2
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            Lirussi-Igor-CV.pdf
            Lirussi-Igor-CV-Ita.pdf

          
  TelegramJobFailure:
      needs: [BuildLatexJob] #when finished this job
      if: failure() # if its failed
      runs-on: ubuntu-20.04
      steps:
      - name: Clone Repo with Checkout 
        uses: actions/checkout@v2 # clones repo! Action implemented in this repository, tag "2"
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Logs
      - name: Send custom Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              ${{ github.event_name }} event,
              on github.com/${{ github.repository }}, 
              by ${{ github.actor }}.
              /!\ FAILED /!\
          disable_web_page_preview: true
          document: small.log
          
  
  DeployJob:
    needs: BuildLatexJob
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repo with Checkout 
        uses: actions/checkout@v2 # clones repo! Action implemented in this repository, tag "2"
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Artifacts
      - name: Extract Date
        shell: bash
        id: extract_date
        run: |
          echo "::set-output name=DATE::Release-$(date +%F_%H-%M)"
      - name: Print Output Step
        run: echo ${{ steps.extract_date.outputs.DATE }}
      - name: Create relese 
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ steps.extract_date.outputs.DATE }}
          release_name: ${{ steps.extract_date.outputs.DATE }}
          draft: false
          prerelease: false
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.NAME }}"
          TAG="${{ steps.extract_date.outputs.DATE }}"
          MSG="${{ github.event.head_commit.message }}"
          echo $TAG
          hub release create -m "$MSG" "$TAG" || true #crea release con messaggio uguale a MSG)
          while IFS= read -r file; do
            pdf="${file%.*}.pdf"
            echo "Delivering file $pdf"
            gh release upload "$TAG" "$pdf" --clobber
          done 

  TelegramJobDeploy:
      needs: [DeployJob] #when finished this job
      if: success() # if its failed
      runs-on: ubuntu-20.04
      steps:
      - name: Clone Repo with Checkout # first step
        uses: actions/checkout@v2 # clones repo! Action implemented in this repository, tag "2"
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Artifacts
      - name: Send custom Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              RELEASE,
              on github.com/${{ github.repository }}
              commit: ${{github.event.head_commit.message}}
          disable_web_page_preview: true
          document: Lirussi-Igor-CV.pdf
          
 
